### ISSUE TITLE
How to use cli using springboot ?

### ISSUE THREAD

**Issue by alex1232212** [webhooksite/cli#1]
Hi
thanks for code-sharing, i see you are using nodejs.

Is it possible to use springboot application to fetch data from webhooks.site? if yes could you show me an example plz?
I already opend an issue using stackoverflow: 
https://stackoverflow.com/questions/71100511/status-page-with-webhook-site-and-springboot
thanks
alex

**Comment by fredsted** [comment]
Hi Alex, it sounds like you could use the API to fetch data sent to a Webhook.site URL: https://docs.webhook.site/api/tokens.html#get-requests
