### ISSUE TITLE
Unable to disable two way proxying with --listen-timeout=0

### ISSUE THREAD

**Issue by marvinroger** [webhooksite/cli#5]
Hi, thank you for this great tool!

Setting the `listen-timeout` to `0` does not work because of this line: https://github.com/webhooksite/cli/blob/f06d37764bfff447bed21ce997d1722d2e2e8f7a/commands/forward.js#L63

The request is aborted right away. I think this line misses a conditional.

**Comment by fredsted** [comment]
Hello Marvin
I believe this was fixed in commit [058f2ad](https://github.com/webhooksite/cli/commit/058f2ad21a5ea12b6918c839d524f1f4c7892bdd). Thanks for reporting it.
